"""
Django settings for mc project.

Generated by 'django-admin startproject' using Django 4.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

import os
from email.message import Message
from pathlib import Path

import mc.db as db  # importacion para la creacion de la configuracion de BD

# Build paths inside the project like this: BASE_DIR / 'subdir'.
#BASE_DIR = Path(__file__).resolve().parent.parent
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Media files
MEDIA_URL = 'media/'
MEDIAFILES_DIRS = (
    os.path.join(BASE_DIR,'media'),
)



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-u$_yhgg&n02ki2g#2p7%*k^t@cgdcy$m&5(%zwlbh00vw1c962'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOST = ['*']

MESSAGE_STORAGE = "django.contrib.messages.storage.cookie.CookieStorage"

JAZZMIN_SETTINGS = {
    # Texto de bienvenida en la pantalla de inicio de sesión
    "welcome_sign": "Bienvenidos",

    # Título de la marca (19 caracteres como máximo) (predeterminado en current_admin_site.site_header si está ausente o Ninguno)
    "site_brand": "Administración",
    
    # Logo para usar para su sitio, debe estar presente en archivos estáticos, utilizados para la marca en la parte superior izquierda
   "site_logo": "../static/images/logoAdmin.png",

    # título de la ventana (el valor predeterminado será current_admin_site.site_title si está ausente o Ninguno)
    "site_title": "MediConsult",

    # Título en la pantalla de inicio de sesión (19 caracteres como máximo) (el valor predeterminado es current_admin_site.site_header si está ausente o Ninguno)
    "site_header": "MediConsult",

    # Darle una forma CSS aL Logo
    "site_logo_classes": False,

    # La ruta relativa a un favicon para su sitio, por defecto será site_logo si está ausente (idealmente 32x32 px)
    "site_icon": "../static/images/gt_favicon.png",

   # Enlaces para poner a lo largo del menú superior
    "topmenu_links": [

        # Url that gets reversed (Permissions can be added)
        {"name": "Inicio",  "url": "admin:index", "permissions": ["auth.view_user"]},

      
        # model admin to link to (Permissions checked against model)
        {"model": "auth.User"},
    ],

    #El administrador del modelo para buscar desde la barra de búsqueda, la barra de búsqueda se omite si se excluye
    #"search_model": "appmc.modelos",

    # Agregar iconos para los modelos
"icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "appmc.Medical":"fa fa-user-md",
        "appmc.Medicine":"fa fa-plus-square",
        "appmc.ClinicHistory":"fa fa-archive",
        "appmc.User":"fa fa-user-plus",
        "appmc.EvolutionTreatment":"fa fa-file",
        "appmc.DentalChart":"fa fa-book",
        "appmc.Treatment":"fa fa-folder",
        "appmc.PatientTooth": "fa fa-tooth",
        "appmc.Allergies":"fa fa-allergies",
        "appmc.Background":"fa fa-history",
        "appmc.Appointment":"fa fa-calendar-day",
        "appmc.Payment":"fa fa-money-bill",
    },

     #Se muestra el menú lateral
    "show_sidebar":True,

    #Se va a expandir automáticamente el menú
    "navigation_expanded": True,

    # Derechos de autor en el pie de página
    "copyright": "MediConsult",

}

#JAZZMIN_UI_TWEAKS = {
#    "theme": "flatly",
#    "dark_mode_theme": "darkly",
#}

# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'admin_interface',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'colorfield',
    'import_export',
    'appmc',

]


X_FRAME_OPTIONS='SAMEORIGIN'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    #'django.contrib.auth.middleware.SessionAuthenticationMiddleware',   
    
]

ROOT_URLCONF = 'mc.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mc.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = db.SQLITE


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

#LANGUAGE_CODE = 'en-us'
LANGUAGE_CODE = 'es-co'


#TIME_ZONE = 'UTC'
TIME_ZONE = 'America/Bogota'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static'),
)

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Enviar emails
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'medicconsutlsoft23@gmail.com'
EMAIL_HOST_PASSWORD = 'ufhddiihdlhlavxc' 
EMAIL_PORT = 587
EMAIL_USE_TLS = True


# Agregar ruta de STATIC_ROOT
STATIC_ROOT = BASE_DIR / 'static'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
